### ISSUE TITLE
[Feature]: Disable option for images

### ISSUE THREAD

**Issue by sstrubberg** [michaelcontento/credly2hugo-action#2]
hey @michaelcontento, i ran into your GH Action as a stumbled the internet looking for a way to display my badges on my personal website that uses NextJs. The raw data file your tool produces in clutch. It has everything I could possibly need, including URLs to the image files themselves, making the pngs that are downloaded unnecessary for my needs. I was curious if you were interested in tossing in a configuration that allowed a consumer to disable the images downloaded. Thanks for considering the request. Love the tool!

**Comment by michaelcontento** [comment]
Hi @sstrubberg,

yes, I do like the idea of having an optional flag to skip the image downloading! 
Let me see when I have some spare time to implement it :-)

Thanks a lot!

**Comment by michaelcontento** [comment]
Hey @sstrubberg,

I've created a whole new action that it not tied to Hugo at all and also supports skipping the image download part.

Give it a try if you want to: https://github.com/michaelcontento/credly-import-action 

😄 🍻

**Comment by michaelcontento** [comment]
Hi @sstrubberg,

did you had the chance to have a look on https://github.com/michaelcontento/credly-import-action ?

Does it suit your needs?

I'd like to close this issue :-)

**Comment by sstrubberg** [comment]
Works like a champ! Thank you so much.

https://www.scottstrubberg.com/dashboard
