### ISSUE TITLE
[Bug]: pathing

### ISSUE THREAD

**Issue by sstrubberg** [michaelcontento/credly2hugo-action#3]
Here's my configuration:
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/15822070/207042826-5d0a10c3-23ff-4466-91b5-ecf39e2643be.png">

It's pretty identical to yours, except I have my pathing configured differently. My intention was to drop the scraped files into wholly new directories, however, what ends up happening is that they are placed in the directories I configure *inside* the `assets` and `data`, respectively.

<img width="814" alt="image" src="https://user-images.githubusercontent.com/15822070/207043279-787cb0bb-34db-4a03-b3d5-3d03e6459d3b.png">

<img width="922" alt="image" src="https://user-images.githubusercontent.com/15822070/207044293-f312cddf-4433-437c-bc3e-068aeb9ae416.png">

My hope is that I have just misconfigured because I noticed you had done some [fixes](https://github.com/michaelcontento/credly2hugo-action/commit/88eddcd4e904a20958d4d65c5e0fc23b700388ca) very recently to the pathing.

Thanks for your help. Again, great tool you got here :)

**Comment by michaelcontento** [comment]
Hi,

yes, this is currently a "bug" in the script, as it's tailored towards Hugo. 
But when I have some spare time I will re-visit and solve this, as the user experience is not that well currently :-( 

Maybe I should split this into two actions? One "more general" and one tied towards hugoo (with some path conventions for example)? 

What do you think?

**Comment by sstrubberg** [comment]
That could work. Happy to test it out.

**Comment by michaelcontento** [comment]
I'll close this as we now have [credly-import-action](https://github.com/michaelcontento/credly-import-action) as generic (as in: not tailed towards hugo) action available that also does not suffer from this pathing bias.
